# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/1Study/5-CV/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(761, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pico = QtWidgets.QLabel(self.centralwidget)
        self.pico.setScaledContents(False)
        self.pico.setObjectName("pico")
        self.horizontalLayout_2.addWidget(self.pico)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.do_detec = QtWidgets.QPushButton(self.centralwidget)
        self.do_detec.setObjectName("do_detec")
        self.horizontalLayout_5.addWidget(self.do_detec)
        self.open_file = QtWidgets.QPushButton(self.centralwidget)
        self.open_file.setObjectName("open_file")
        self.horizontalLayout_5.addWidget(self.open_file)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cap10 = QtWidgets.QLabel(self.centralwidget)
        self.cap10.setObjectName("cap10")
        self.verticalLayout_11.addWidget(self.cap10)
        self.label10 = QtWidgets.QLabel(self.centralwidget)
        self.label10.setObjectName("label10")
        self.verticalLayout_11.addWidget(self.label10)
        self.verticalLayout_11.setStretch(0, 5)
        self.verticalLayout_11.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_11, 4, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cap5 = QtWidgets.QLabel(self.centralwidget)
        self.cap5.setObjectName("cap5")
        self.verticalLayout_7.addWidget(self.cap5)
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setObjectName("label5")
        self.verticalLayout_7.addWidget(self.label5)
        self.verticalLayout_7.setStretch(0, 5)
        self.verticalLayout_7.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cap7 = QtWidgets.QLabel(self.centralwidget)
        self.cap7.setObjectName("cap7")
        self.verticalLayout_9.addWidget(self.cap7)
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setObjectName("label7")
        self.verticalLayout_9.addWidget(self.label7)
        self.verticalLayout_9.setStretch(0, 5)
        self.verticalLayout_9.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_9, 3, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cap9 = QtWidgets.QLabel(self.centralwidget)
        self.cap9.setObjectName("cap9")
        self.verticalLayout_10.addWidget(self.cap9)
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setObjectName("label9")
        self.verticalLayout_10.addWidget(self.label9)
        self.verticalLayout_10.setStretch(0, 5)
        self.verticalLayout_10.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_10, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cap1 = QtWidgets.QLabel(self.centralwidget)
        self.cap1.setObjectName("cap1")
        self.verticalLayout.addWidget(self.cap1)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cap8 = QtWidgets.QLabel(self.centralwidget)
        self.cap8.setObjectName("cap8")
        self.verticalLayout_8.addWidget(self.cap8)
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        self.label8.setObjectName("label8")
        self.verticalLayout_8.addWidget(self.label8)
        self.verticalLayout_8.setStretch(0, 5)
        self.verticalLayout_8.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_8, 3, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cap2 = QtWidgets.QLabel(self.centralwidget)
        self.cap2.setObjectName("cap2")
        self.verticalLayout_2.addWidget(self.cap2)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setObjectName("label2")
        self.verticalLayout_2.addWidget(self.label2)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cap6 = QtWidgets.QLabel(self.centralwidget)
        self.cap6.setObjectName("cap6")
        self.verticalLayout_6.addWidget(self.cap6)
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setObjectName("label6")
        self.verticalLayout_6.addWidget(self.label6)
        self.verticalLayout_6.setStretch(0, 5)
        self.verticalLayout_6.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_6, 2, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cap3 = QtWidgets.QLabel(self.centralwidget)
        self.cap3.setObjectName("cap3")
        self.verticalLayout_5.addWidget(self.cap3)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setObjectName("label3")
        self.verticalLayout_5.addWidget(self.label3)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cap4 = QtWidgets.QLabel(self.centralwidget)
        self.cap4.setObjectName("cap4")
        self.verticalLayout_4.addWidget(self.cap4)
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setObjectName("label4")
        self.verticalLayout_4.addWidget(self.label4)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.verticalLayout_12.addLayout(self.gridLayout)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRetry = QtWidgets.QAction(MainWindow)
        self.actionRetry.setObjectName("actionRetry")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cap Detection"))
        self.pico.setText(_translate("MainWindow", "TextLabel"))
        self.do_detec.setText(_translate("MainWindow", "do detection"))
        self.open_file.setText(_translate("MainWindow", "openfile"))
        self.cap10.setText(_translate("MainWindow", "TextLabel"))
        self.label10.setText(_translate("MainWindow", "TextLabel"))
        self.cap5.setText(_translate("MainWindow", "TextLabel"))
        self.label5.setText(_translate("MainWindow", "TextLabel"))
        self.cap7.setText(_translate("MainWindow", "TextLabel"))
        self.label7.setText(_translate("MainWindow", "TextLabel"))
        self.cap9.setText(_translate("MainWindow", "TextLabel"))
        self.label9.setText(_translate("MainWindow", "TextLabel"))
        self.cap1.setText(_translate("MainWindow", "TextLabel"))
        self.label1.setText(_translate("MainWindow", "TextLabel"))
        self.cap8.setText(_translate("MainWindow", "TextLabel"))
        self.label8.setText(_translate("MainWindow", "TextLabel"))
        self.cap2.setText(_translate("MainWindow", "TextLabel"))
        self.label2.setText(_translate("MainWindow", "TextLabel"))
        self.cap6.setText(_translate("MainWindow", "TextLabel"))
        self.label6.setText(_translate("MainWindow", "TextLabel"))
        self.cap3.setText(_translate("MainWindow", "TextLabel"))
        self.label3.setText(_translate("MainWindow", "TextLabel"))
        self.cap4.setText(_translate("MainWindow", "TextLabel"))
        self.label4.setText(_translate("MainWindow", "TextLabel"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionRetry.setText(_translate("MainWindow", "Retry"))
